FROM ubuntu:14.04
RUN apt-get update

# Install Ansible-devel from github.com:ansible/ansible
RUN apt-get install -y software-properties-common git
RUN git clone https://github.com/ansible/ansible.git --recursive
RUN cd ansible && make && make install

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
